# Generated by Django 4.0.2 on 2022-02-25 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_student', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('preferred_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='profile-image')),
                ('discord_name', models.CharField(max_length=100)),
                ('github_username', models.CharField(max_length=100)),
                ('codepen_username', models.CharField(max_length=100)),
                ('fcc_profile_url', models.URLField(max_length=255)),
                ('current_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert'), (5, 'Master'), (6, 'Grandmaster'), (7, 'Challenger'), (8, 'Legendary')], default='Beginner')),
                ('phone', models.CharField(max_length=20)),
                ('timezone', models.CharField(max_length=50)),
            ],
        ),
    ]
